const CANVAS_SIZE = 2362;
const PANEL_HEIGHT = CANVAS_SIZE / 2;
const isFilePage = window.location.protocol === "file:";

const translations = {
  en: {
    title: "Nameplate Studio",
    intro: "Edit layers on the lower panel. The upper panel is always generated by a 180° rotation.",
    localServerRequired: "Open start.command to enable downloads in Chrome. Chrome blocks image export from file URLs.",
    layers: "Layers",
    addText: "Add text",
    addImage: "Add image",
    moveUp: "Move up",
    moveDown: "Move down",
    duplicate: "Duplicate",
    delete: "Delete",
    selectedLayer: "Selected layer",
    selectLayer: "Select a layer to edit it.",
    content: "Content",
    positionX: "Position X",
    positionY: "Position Y",
    font: "Font",
    size: "Size",
    color: "Color",
    shadow: "Shadow",
    shadowColor: "Shadow color",
    opacity: "Opacity",
    blur: "Blur",
    offsetX: "Offset X",
    offsetY: "Offset Y",
    width: "Width",
    uploadFont: "Upload custom font",
    loadSystemFonts: "Load system fonts",
    systemFontsNote: "Requests browser permission to list installed fonts.",
    systemFontsLoaded: "Loaded {count} system font families.",
    systemFontsUnavailable: "This browser cannot list system fonts. Use the built-in list or upload a font.",
    systemFontsDenied: "System font permission was not granted.",
    batchExport: "Batch export",
    importSheet: "Import spreadsheet",
    nameColumn: "Name column",
    numberColumn: "Number column",
    batchEmpty: "Import a spreadsheet to prepare batch export.",
    batchReady: "{count} rows ready for batch export.",
    batchMissingColumns: "Choose both the name and number columns.",
    batchMissingLayers: "Keep one Name layer and one Number layer for batch export.",
    batchProcessing: "Rendering {current}/{total}…",
    batchZipping: "Creating ZIP…",
    batchDone: "ZIP downloaded: {count} PNG files.",
    downloadZip: "Download ZIP",
    sheetError: "Unable to read this spreadsheet.",
    language: "Interface language",
    download: "Download PNG",
    reset: "Reset",
    ready: "Ready to export.",
    preview: "Preview",
    editor: "Lower panel editor",
    fullCard: "Full card",
    deskPreview: "Desk nameplate",
    dragHint: "Drag a layer directly on the lower panel to position it.",
    deskHint: "Perspective preview only. PNG export remains the flat full card.",
    nameLayer: "Name",
    numberLayer: "Number",
    textLayer: "Text",
    imageLayer: "Image",
    downloaded: "PNG downloaded.",
    loading: "Loading artwork and fonts…",
    fontLoaded: "Custom font loaded: {name}",
    imageAdded: "Image layer added.",
    error: "Unable to load the template. Start the local server and refresh.",
    fileError: "Unable to load that file.",
  },
  "zh-CN": {
    title: "桌面铭牌工作室",
    intro: "只编辑下半区图层，上半区始终由下半区旋转 180°生成。",
    localServerRequired: "请双击 start.command 后再导出。Chrome 会拦截 file:// 本地文件页的图片导出。",
    layers: "图层",
    addText: "添加文本",
    addImage: "添加图片",
    moveUp: "上移",
    moveDown: "下移",
    duplicate: "复制",
    delete: "删除",
    selectedLayer: "选中图层",
    selectLayer: "请选择一个图层进行编辑。",
    content: "内容",
    positionX: "水平位置",
    positionY: "垂直位置",
    font: "字体",
    size: "字号",
    color: "颜色",
    shadow: "阴影",
    shadowColor: "阴影颜色",
    opacity: "透明度",
    blur: "模糊",
    offsetX: "水平偏移",
    offsetY: "垂直偏移",
    width: "宽度",
    uploadFont: "上传自定义字体",
    loadSystemFonts: "加载系统字体",
    systemFontsNote: "点击后会请求浏览器权限，以列出本机已安装字体。",
    systemFontsLoaded: "已加载 {count} 个系统字体系列。",
    systemFontsUnavailable: "当前浏览器无法列出系统字体，可使用内置字体或上传字体文件。",
    systemFontsDenied: "未授予读取系统字体的权限。",
    batchExport: "批量导出",
    importSheet: "导入表格",
    nameColumn: "姓名列",
    numberColumn: "编号列",
    batchEmpty: "导入表格后即可准备批量导出。",
    batchReady: "已识别 {count} 条，可批量导出。",
    batchMissingColumns: "请选择姓名列和编号列。",
    batchMissingLayers: "批量导出需要保留一个“姓名”和一个“编号”图层。",
    batchProcessing: "正在生成 {current}/{total}…",
    batchZipping: "正在打包 ZIP…",
    batchDone: "ZIP 已下载：共 {count} 张 PNG。",
    downloadZip: "下载 ZIP",
    sheetError: "无法读取这个表格文件。",
    language: "界面语言",
    download: "下载 PNG",
    reset: "重置",
    ready: "可以导出了。",
    preview: "预览",
    editor: "下半区编辑",
    fullCard: "完整卡片",
    deskPreview: "桌面铭牌",
    dragHint: "直接拖动画布中的图层即可调整位置。",
    deskHint: "这里只模拟透视效果，PNG 仍导出平面完整卡片。",
    nameLayer: "姓名",
    numberLayer: "编号",
    textLayer: "文本",
    imageLayer: "图片",
    downloaded: "PNG 已下载。",
    loading: "正在加载底图和字体…",
    fontLoaded: "自定义字体已加载：{name}",
    imageAdded: "图片图层已添加。",
    error: "无法加载底图，请启动本地服务后刷新页面。",
    fileError: "无法加载该文件。",
  },
};

const template = new Image();
const canvas = document.querySelector("#cardCanvas");
const context = canvas.getContext("2d");
const editorCanvas = document.querySelector("#editorCanvas");
const editorContext = editorCanvas.getContext("2d");
const deskCanvas = document.querySelector("#deskCanvas");
const deskContext = deskCanvas.getContext("2d");
const panelCanvas = document.createElement("canvas");
panelCanvas.width = CANVAS_SIZE;
panelCanvas.height = PANEL_HEIGHT;
const panelContext = panelCanvas.getContext("2d");

const status = document.querySelector("#status");
const language = document.querySelector("#language");
const layerList = document.querySelector("#layerList");
const layerCount = document.querySelector("#layerCount");
const layerInspector = document.querySelector("#layerInspector");
const emptyInspector = document.querySelector("#emptyInspector");
const canvasLayerActions = document.querySelector("#canvasLayerActions");
const localFileNotice = document.querySelector("#localFileNotice");
const batchControls = {
  file: document.querySelector("#batchFile"),
  nameColumn: document.querySelector("#batchNameColumn"),
  numberColumn: document.querySelector("#batchNumberColumn"),
  summary: document.querySelector("#batchSummary"),
  progress: document.querySelector("#batchProgress"),
  exportButton: document.querySelector("#batchExportButton"),
};

const controls = {
  text: document.querySelector("#layerText"),
  x: document.querySelector("#layerX"),
  y: document.querySelector("#layerY"),
  font: document.querySelector("#layerFont"),
  size: document.querySelector("#layerSize"),
  color: document.querySelector("#layerColor"),
  shadowEnabled: document.querySelector("#layerShadowEnabled"),
  shadowColor: document.querySelector("#layerShadowColor"),
  shadowOpacity: document.querySelector("#layerShadowOpacity"),
  shadowBlur: document.querySelector("#layerShadowBlur"),
  shadowX: document.querySelector("#layerShadowX"),
  shadowY: document.querySelector("#layerShadowY"),
  imageWidth: document.querySelector("#layerImageWidth"),
  imageOpacity: document.querySelector("#layerImageOpacity"),
};

const outputs = {
  size: document.querySelector("#layerSizeValue"),
  shadowOpacity: document.querySelector("#layerShadowOpacityValue"),
  shadowBlur: document.querySelector("#layerShadowBlurValue"),
  shadowX: document.querySelector("#layerShadowXValue"),
  shadowY: document.querySelector("#layerShadowYValue"),
  imageWidth: document.querySelector("#layerImageWidthValue"),
  imageOpacity: document.querySelector("#layerImageOpacityValue"),
};

let layers = [];
let selectedLayerId = null;
let nextLayerId = 1;
let templateReady = false;
let dragState = null;
let uploadedFontUrl = null;
let batchRows = [];
let batchHeaders = [];
let systemFontsLoaded = false;
let layerActionHideTimer = null;

function createTextLayer(options = {}) {
  return {
    id: `layer-${nextLayerId++}`,
    type: "text",
    role: options.role ?? null,
    label: options.label ?? null,
    visible: true,
    text: options.text ?? t("textLayer"),
    x: options.x ?? CANVAS_SIZE / 2,
    y: options.y ?? PANEL_HEIGHT / 2,
    maxWidth: options.maxWidth ?? 1500,
    font: options.font ?? "ZCOOL KuaiLe",
    size: options.size ?? 360,
    color: options.color ?? "#627ef5",
    outline: options.outline ?? true,
    shadow: {
      enabled: options.shadow?.enabled ?? true,
      color: options.shadow?.color ?? "#1e232d",
      opacity: options.shadow?.opacity ?? 48,
      blur: options.shadow?.blur ?? 24,
      x: options.shadow?.x ?? 13,
      y: options.shadow?.y ?? 24,
    },
  };
}

function createDefaultLayers() {
  return [
    createTextLayer({
      role: "name",
      text: "游诗妤",
      x: 930,
      y: 629,
      maxWidth: 1530,
      size: 430,
    }),
    createTextLayer({
      role: "number",
      text: "07",
      x: 2070,
      y: 214,
      maxWidth: 515,
      font: "Anton",
      size: 410,
      color: "#ffffff",
      outline: false,
      shadow: { enabled: false, color: "#1e232d", opacity: 35, blur: 15, x: 8, y: 12 },
    }),
  ];
}

function getLocale() {
  return language.value in translations ? language.value : "en";
}

function t(key) {
  return translations[getLocale()][key] ?? translations.en[key] ?? key;
}

function setStatus(key, replacements = {}) {
  let message = t(key);
  Object.entries(replacements).forEach(([name, value]) => {
    message = message.replace(`{${name}}`, value);
  });
  status.textContent = message;
}

function applyTranslations() {
  document.documentElement.lang = getLocale();
  document.querySelectorAll("[data-i18n]").forEach((element) => {
    element.textContent = t(element.dataset.i18n);
  });
  document.querySelectorAll("[data-tooltip]").forEach((element) => {
    const label = t(element.dataset.tooltip);
    element.title = label;
    element.setAttribute("aria-label", label);
  });
  renderLayerList();
  updateBatchUi();
}

function updateFileModeNotice() {
  localFileNotice.hidden = !isFilePage;
}

function cssFontFamily(family) {
  return family.includes(" ") ? `"${family}"` : family;
}

function fitFontSize(targetContext, layer) {
  let size = layer.size;
  while (size > 60) {
    targetContext.font = `${size}px ${cssFontFamily(layer.font)}`;
    if (targetContext.measureText(layer.text).width <= layer.maxWidth) return size;
    size -= 4;
  }
  return 60;
}

function hexToRgba(hex, alphaPercent) {
  const normalized = hex.replace("#", "");
  const number = Number.parseInt(normalized, 16);
  const red = (number >> 16) & 255;
  const green = (number >> 8) & 255;
  const blue = number & 255;
  return `rgba(${red}, ${green}, ${blue}, ${alphaPercent / 100})`;
}

function drawTextLayer(targetContext, layer) {
  if (!layer.text) return;
  const fontSize = fitFontSize(targetContext, layer);
  targetContext.save();
  targetContext.font = `${fontSize}px ${cssFontFamily(layer.font)}`;
  targetContext.textAlign = "center";
  targetContext.textBaseline = "middle";
  targetContext.lineJoin = "round";
  targetContext.miterLimit = 2;
  targetContext.lineWidth = Math.max(20, fontSize * 0.075);
  targetContext.strokeStyle = "#ffffff";
  targetContext.fillStyle = layer.color;

  if (layer.shadow.enabled) {
    targetContext.shadowColor = hexToRgba(layer.shadow.color, layer.shadow.opacity);
    targetContext.shadowBlur = layer.shadow.blur;
    targetContext.shadowOffsetX = layer.shadow.x;
    targetContext.shadowOffsetY = layer.shadow.y;
    if (layer.outline) targetContext.strokeText(layer.text, layer.x, layer.y, layer.maxWidth);
    targetContext.fillText(layer.text, layer.x, layer.y, layer.maxWidth);
    targetContext.shadowColor = "transparent";
    targetContext.shadowBlur = 0;
    targetContext.shadowOffsetX = 0;
    targetContext.shadowOffsetY = 0;
  }

  if (layer.outline) targetContext.strokeText(layer.text, layer.x, layer.y, layer.maxWidth);
  targetContext.fillText(layer.text, layer.x, layer.y, layer.maxWidth);
  targetContext.restore();
}

function drawImageLayer(targetContext, layer) {
  if (!layer.image?.complete) return;
  const height = layer.width / layer.aspectRatio;
  targetContext.save();
  targetContext.globalAlpha = layer.opacity / 100;
  targetContext.drawImage(layer.image, layer.x - layer.width / 2, layer.y - height / 2, layer.width, height);
  targetContext.restore();
}

function drawLayer(targetContext, layer) {
  if (!layer.visible) return;
  if (layer.type === "text") drawTextLayer(targetContext, layer);
  if (layer.type === "image") drawImageLayer(targetContext, layer);
}

function getLayerBounds(layer, targetContext = editorContext) {
  if (layer.type === "image") {
    const height = layer.width / layer.aspectRatio;
    return { x: layer.x - layer.width / 2, y: layer.y - height / 2, width: layer.width, height };
  }

  const fontSize = fitFontSize(targetContext, layer);
  targetContext.save();
  targetContext.font = `${fontSize}px ${cssFontFamily(layer.font)}`;
  const measuredWidth = Math.min(targetContext.measureText(layer.text || " ").width, layer.maxWidth);
  targetContext.restore();
  const padding = Math.max(24, fontSize * 0.1);
  return {
    x: layer.x - measuredWidth / 2 - padding,
    y: layer.y - fontSize * 0.58 - padding,
    width: measuredWidth + padding * 2,
    height: fontSize * 1.16 + padding * 2,
  };
}

function drawSelection(targetContext) {
  const layer = getSelectedLayer();
  if (!layer?.visible) return;
  const bounds = getLayerBounds(layer, targetContext);
  targetContext.save();
  targetContext.strokeStyle = "#315af5";
  targetContext.lineWidth = 5;
  targetContext.setLineDash([16, 10]);
  targetContext.strokeRect(bounds.x, bounds.y, bounds.width, bounds.height);
  targetContext.fillStyle = "#ffffff";
  targetContext.strokeStyle = "#315af5";
  targetContext.setLineDash([]);
  for (const [x, y] of [
    [bounds.x, bounds.y],
    [bounds.x + bounds.width, bounds.y],
    [bounds.x, bounds.y + bounds.height],
    [bounds.x + bounds.width, bounds.y + bounds.height],
  ]) {
    targetContext.beginPath();
    targetContext.arc(x, y, 10, 0, Math.PI * 2);
    targetContext.fill();
    targetContext.stroke();
  }
  targetContext.restore();
}

function renderPanel(targetContext, includeSelection = false) {
  targetContext.clearRect(0, 0, CANVAS_SIZE, PANEL_HEIGHT);
  targetContext.drawImage(
    template,
    0,
    PANEL_HEIGHT,
    CANVAS_SIZE,
    PANEL_HEIGHT,
    0,
    0,
    CANVAS_SIZE,
    PANEL_HEIGHT,
  );
  layers.forEach((layer) => drawLayer(targetContext, layer));
  if (includeSelection) drawSelection(targetContext);
}

function render() {
  if (!templateReady) return;
  renderPanel(panelContext, false);
  renderPanel(editorContext, true);

  context.clearRect(0, 0, CANVAS_SIZE, CANVAS_SIZE);
  context.drawImage(panelCanvas, 0, PANEL_HEIGHT);
  context.save();
  context.translate(CANVAS_SIZE, PANEL_HEIGHT);
  context.rotate(Math.PI);
  context.drawImage(panelCanvas, 0, 0);
  context.restore();

  deskContext.clearRect(0, 0, CANVAS_SIZE, PANEL_HEIGHT);
  deskContext.drawImage(panelCanvas, 0, 0);
}

function getSelectedLayer() {
  return layers.find((layer) => layer.id === selectedLayerId) ?? null;
}

function getLayerName(layer) {
  if (layer.role === "name") return t("nameLayer");
  if (layer.role === "number") return t("numberLayer");
  if (layer.type === "image") return layer.label || t("imageLayer");
  return layer.label || layer.text || t("textLayer");
}

function renderLayerList() {
  if (!layerList) return;
  layerList.replaceChildren();
  [...layers].reverse().forEach((layer) => {
    const row = document.createElement("div");
    row.className = `layer-row${layer.id === selectedLayerId ? " selected" : ""}`;

    const visibility = document.createElement("input");
    visibility.type = "checkbox";
    visibility.checked = layer.visible;
    visibility.title = "Visibility";
    visibility.addEventListener("change", () => {
      layer.visible = visibility.checked;
      render();
    });

    const selectButton = document.createElement("button");
    selectButton.type = "button";
    selectButton.className = "layer-select";
    selectButton.textContent = `${layer.type === "text" ? "T" : "▧"}  ${getLayerName(layer)}`;
    selectButton.addEventListener("click", () => selectLayer(layer.id));

    row.append(visibility, selectButton);
    layerList.append(row);
  });
  layerCount.textContent = String(layers.length);
}

function updateControlOutputs() {
  outputs.size.value = controls.size.value;
  outputs.shadowOpacity.value = `${controls.shadowOpacity.value}%`;
  outputs.shadowBlur.value = controls.shadowBlur.value;
  outputs.shadowX.value = controls.shadowX.value;
  outputs.shadowY.value = controls.shadowY.value;
  outputs.imageWidth.value = controls.imageWidth.value;
  outputs.imageOpacity.value = `${controls.imageOpacity.value}%`;
}

function updateShadowAvailability() {
  const disabled = !controls.shadowEnabled.checked;
  const shadowControls = document.querySelector("#shadowControls");
  shadowControls.setAttribute("aria-disabled", String(disabled));
  shadowControls.querySelectorAll("input").forEach((input) => {
    input.disabled = disabled;
  });
}

function syncInspector() {
  const layer = getSelectedLayer();
  layerInspector.hidden = !layer;
  emptyInspector.hidden = Boolean(layer);
  document.querySelectorAll(".text-only").forEach((element) => {
    element.hidden = !layer || layer.type !== "text";
  });
  document.querySelectorAll(".image-only").forEach((element) => {
    element.hidden = !layer || layer.type !== "image";
  });
  if (!layer) return;

  controls.x.value = Math.round(layer.x);
  controls.y.value = Math.round(layer.y);
  if (layer.type === "text") {
    controls.text.value = layer.text;
    controls.font.value = layer.font;
    controls.size.value = layer.size;
    controls.color.value = layer.color;
    controls.shadowEnabled.checked = layer.shadow.enabled;
    controls.shadowColor.value = layer.shadow.color;
    controls.shadowOpacity.value = layer.shadow.opacity;
    controls.shadowBlur.value = layer.shadow.blur;
    controls.shadowX.value = layer.shadow.x;
    controls.shadowY.value = layer.shadow.y;
    updateShadowAvailability();
  } else {
    controls.imageWidth.value = Math.round(layer.width);
    controls.imageOpacity.value = layer.opacity;
  }
  updateControlOutputs();
}

function selectLayer(id) {
  selectedLayerId = id;
  hideCanvasLayerActions();
  renderLayerList();
  syncInspector();
  render();
}

function clampLayer(layer) {
  const bounds = getLayerBounds(layer);
  const halfWidth = bounds.width / 2;
  const halfHeight = bounds.height / 2;
  layer.x = Math.max(halfWidth, Math.min(CANVAS_SIZE - halfWidth, layer.x));
  layer.y = Math.max(halfHeight, Math.min(PANEL_HEIGHT - halfHeight, layer.y));
}

function updateSelectedLayerFromInspector(event) {
  const layer = getSelectedLayer();
  if (!layer) return;
  layer.x = Number(controls.x.value);
  layer.y = Number(controls.y.value);

  if (layer.type === "text") {
    layer.text = controls.text.value;
    layer.font = controls.font.value;
    layer.size = Number(controls.size.value);
    layer.color = controls.color.value;
    layer.shadow.enabled = controls.shadowEnabled.checked;
    layer.shadow.color = controls.shadowColor.value;
    layer.shadow.opacity = Number(controls.shadowOpacity.value);
    layer.shadow.blur = Number(controls.shadowBlur.value);
    layer.shadow.x = Number(controls.shadowX.value);
    layer.shadow.y = Number(controls.shadowY.value);
  } else {
    layer.width = Number(controls.imageWidth.value);
    layer.opacity = Number(controls.imageOpacity.value);
  }

  clampLayer(layer);
  controls.x.value = Math.round(layer.x);
  controls.y.value = Math.round(layer.y);
  updateControlOutputs();
  updateShadowAvailability();
  if (event?.target === controls.text) renderLayerList();
  render();
}

function addTextLayer() {
  const layer = createTextLayer({
    text: t("textLayer"),
    x: CANVAS_SIZE / 2,
    y: PANEL_HEIGHT / 2,
    size: 300,
  });
  layers.push(layer);
  selectLayer(layer.id);
  controls.text.focus();
  controls.text.select();
}

async function addImageLayer(file) {
  if (!file) return;
  const objectUrl = URL.createObjectURL(file);
  const image = new Image();
  try {
    await new Promise((resolve, reject) => {
      image.addEventListener("load", resolve, { once: true });
      image.addEventListener("error", reject, { once: true });
      image.src = objectUrl;
    });
    const layer = {
      id: `layer-${nextLayerId++}`,
      type: "image",
      role: null,
      label: file.name,
      visible: true,
      image,
      objectUrl,
      aspectRatio: image.naturalWidth / image.naturalHeight,
      x: CANVAS_SIZE / 2,
      y: PANEL_HEIGHT / 2,
      width: Math.min(520, image.naturalWidth),
      opacity: 100,
    };
    layers.push(layer);
    selectLayer(layer.id);
    setStatus("imageAdded");
  } catch (error) {
    console.error(error);
    URL.revokeObjectURL(objectUrl);
    setStatus("fileError");
  }
}

function duplicateSelectedLayer() {
  const layer = getSelectedLayer();
  if (!layer) return;
  const copy = {
    ...layer,
    id: `layer-${nextLayerId++}`,
    role: null,
    label: `${getLayerName(layer)} copy`,
    x: layer.x + 45,
    y: layer.y + 45,
    shadow: layer.type === "text" ? { ...layer.shadow } : undefined,
  };
  clampLayer(copy);
  layers.push(copy);
  selectLayer(copy.id);
}

function deleteSelectedLayer() {
  const index = layers.findIndex((layer) => layer.id === selectedLayerId);
  if (index < 0) return;
  const [removed] = layers.splice(index, 1);
  if (removed.type === "image" && removed.objectUrl) URL.revokeObjectURL(removed.objectUrl);
  selectedLayerId = layers[Math.min(index, layers.length - 1)]?.id ?? null;
  renderLayerList();
  syncInspector();
  render();
}

function moveSelectedLayer(direction) {
  const index = layers.findIndex((layer) => layer.id === selectedLayerId);
  const nextIndex = index + direction;
  if (index < 0 || nextIndex < 0 || nextIndex >= layers.length) return;
  [layers[index], layers[nextIndex]] = [layers[nextIndex], layers[index]];
  renderLayerList();
  render();
}

function reset() {
  layers.forEach((layer) => {
    if (layer.type === "image" && layer.objectUrl) URL.revokeObjectURL(layer.objectUrl);
  });
  layers = createDefaultLayers();
  selectedLayerId = layers[0].id;
  renderLayerList();
  syncInspector();
  render();
  setStatus("ready");
}

function canvasPoint(event) {
  const rect = editorCanvas.getBoundingClientRect();
  return {
    x: ((event.clientX - rect.left) / rect.width) * CANVAS_SIZE,
    y: ((event.clientY - rect.top) / rect.height) * PANEL_HEIGHT,
  };
}

function hitTest(point) {
  for (let index = layers.length - 1; index >= 0; index -= 1) {
    const layer = layers[index];
    if (!layer.visible) continue;
    const bounds = getLayerBounds(layer);
    if (
      point.x >= bounds.x
      && point.x <= bounds.x + bounds.width
      && point.y >= bounds.y
      && point.y <= bounds.y + bounds.height
    ) return layer;
  }
  return null;
}

function isPointNearLayerBorder(point, layer) {
  const bounds = getLayerBounds(layer);
  const tolerance = 42;
  const withinOuter = (
    point.x >= bounds.x - tolerance
    && point.x <= bounds.x + bounds.width + tolerance
    && point.y >= bounds.y - tolerance
    && point.y <= bounds.y + bounds.height + tolerance
  );
  const withinInner = (
    point.x > bounds.x + tolerance
    && point.x < bounds.x + bounds.width - tolerance
    && point.y > bounds.y + tolerance
    && point.y < bounds.y + bounds.height - tolerance
  );
  return withinOuter && !withinInner;
}

function positionCanvasLayerActions(layer) {
  const bounds = getLayerBounds(layer);
  const rect = editorCanvas.getBoundingClientRect();
  const scaleX = rect.width / CANVAS_SIZE;
  const scaleY = rect.height / PANEL_HEIGHT;
  const halfToolbarWidth = 90;
  const toolbarHeight = 43;
  const actionX = Math.max(
    halfToolbarWidth,
    Math.min(rect.width - halfToolbarWidth, (bounds.x + bounds.width / 2) * scaleX),
  );
  const above = bounds.y * scaleY - toolbarHeight - 10;
  const below = (bounds.y + bounds.height) * scaleY + 10;
  const actionY = above >= 8 ? above : Math.min(rect.height - toolbarHeight - 8, below);
  canvasLayerActions.style.left = `${actionX}px`;
  canvasLayerActions.style.top = `${actionY}px`;
}

function showCanvasLayerActions(layer) {
  window.clearTimeout(layerActionHideTimer);
  positionCanvasLayerActions(layer);
  canvasLayerActions.hidden = false;
}

function hideCanvasLayerActions(delay = 0) {
  window.clearTimeout(layerActionHideTimer);
  layerActionHideTimer = window.setTimeout(() => {
    canvasLayerActions.hidden = true;
  }, delay);
}

editorCanvas.addEventListener("pointerdown", (event) => {
  const point = canvasPoint(event);
  const layer = hitTest(point);
  if (!layer) return;
  selectLayer(layer.id);
  dragState = { offsetX: point.x - layer.x, offsetY: point.y - layer.y };
  editorCanvas.setPointerCapture(event.pointerId);
});

editorCanvas.addEventListener("pointermove", (event) => {
  const point = canvasPoint(event);
  if (!dragState) {
    const layer = getSelectedLayer();
    if (layer?.visible && isPointNearLayerBorder(point, layer)) {
      showCanvasLayerActions(layer);
    } else {
      hideCanvasLayerActions(120);
    }
    return;
  }

  const layer = getSelectedLayer();
  if (!layer) return;
  layer.x = point.x - dragState.offsetX;
  layer.y = point.y - dragState.offsetY;
  clampLayer(layer);
  controls.x.value = Math.round(layer.x);
  controls.y.value = Math.round(layer.y);
  render();
});

editorCanvas.addEventListener("pointerleave", () => hideCanvasLayerActions(120));
canvasLayerActions.addEventListener("pointerenter", () => window.clearTimeout(layerActionHideTimer));
canvasLayerActions.addEventListener("pointerleave", () => hideCanvasLayerActions(120));
canvasLayerActions.addEventListener("pointerdown", (event) => event.stopPropagation());
canvasLayerActions.addEventListener("click", (event) => {
  const button = event.target.closest("[data-layer-action]");
  if (!button) return;
  const action = button.dataset.layerAction;
  if (action === "up") moveSelectedLayer(1);
  if (action === "down") moveSelectedLayer(-1);
  if (action === "duplicate") duplicateSelectedLayer();
  if (action === "delete") deleteSelectedLayer();
  hideCanvasLayerActions();
});

function endDrag(event) {
  if (dragState && editorCanvas.hasPointerCapture(event.pointerId)) {
    editorCanvas.releasePointerCapture(event.pointerId);
  }
  dragState = null;
}

editorCanvas.addEventListener("pointerup", endDrag);
editorCanvas.addEventListener("pointercancel", endDrag);

function safeFilenamePart(value, fallback) {
  const cleaned = value.trim().replace(/[\\/:*?"<>|\s]+/g, "-");
  return cleaned || fallback;
}

async function downloadPng() {
  if (isFilePage) {
    setStatus("localServerRequired");
    return;
  }
  render();
  const nameLayer = layers.find((layer) => layer.role === "name");
  const numberLayer = layers.find((layer) => layer.role === "number");
  const filename = `${safeFilenamePart(nameLayer?.text ?? "nameplate", "nameplate")}-${safeFilenamePart(
    numberLayer?.text ?? "card",
    "card",
  )}.png`;
  try {
    downloadBlob(await canvasToBlob(canvas), filename);
    setStatus("downloaded");
  } catch (error) {
    console.error(error);
    setStatus("fileError");
  }
}

async function loadCustomFont(file) {
  if (!file) return;
  if (uploadedFontUrl) URL.revokeObjectURL(uploadedFontUrl);
  uploadedFontUrl = URL.createObjectURL(file);
  const family = `Custom Font ${Date.now()}`;
  try {
    const fontFace = new FontFace(family, `url(${uploadedFontUrl})`);
    await fontFace.load();
    document.fonts.add(fontFace);
    const option = document.createElement("option");
    option.value = family;
    option.textContent = file.name;
    controls.font.append(option);
    const layer = getSelectedLayer();
    if (layer?.type === "text") {
      layer.font = family;
      controls.font.value = family;
      render();
    }
    setStatus("fontLoaded", { name: file.name });
  } catch (error) {
    console.error(error);
    setStatus("fileError");
  }
}

function createFontOption(family, label = family) {
  const option = document.createElement("option");
  option.value = family;
  option.textContent = label;
  return option;
}

async function loadSystemFonts() {
  if (!window.queryLocalFonts) {
    setStatus("systemFontsUnavailable");
    return;
  }

  try {
    const fontData = await window.queryLocalFonts();
    const families = [...new Set(fontData.map((font) => font.family).filter(Boolean))]
      .sort((first, second) => first.localeCompare(second));
    const existing = new Set([...controls.font.options].map((option) => option.value));
    const oldGroup = controls.font.querySelector("optgroup[data-system-fonts]");
    oldGroup?.remove();

    const group = document.createElement("optgroup");
    group.label = "System Fonts";
    group.dataset.systemFonts = "true";
    families.filter((family) => !existing.has(family)).forEach((family) => {
      group.append(createFontOption(family));
    });
    controls.font.append(group);
    systemFontsLoaded = true;
    setStatus("systemFontsLoaded", { count: families.length });
  } catch (error) {
    console.warn("System font access was not granted.", error);
    setStatus(error.name === "NotAllowedError" ? "systemFontsDenied" : "systemFontsUnavailable");
  }
}

function getColumnLabel(index) {
  const header = batchHeaders[index] || `${t("content")} ${index + 1}`;
  return `${String.fromCharCode(65 + index)} — ${header}`;
}

function findSuggestedColumn(pattern, fallbackIndex) {
  const index = batchHeaders.findIndex((header) => pattern.test(header));
  return index >= 0 ? index : fallbackIndex;
}

function fillColumnSelect(select, selectedIndex) {
  select.replaceChildren();
  batchHeaders.forEach((_, index) => {
    const option = document.createElement("option");
    option.value = String(index);
    option.textContent = getColumnLabel(index);
    select.append(option);
  });
  select.value = String(Math.max(0, Math.min(selectedIndex, batchHeaders.length - 1)));
  select.disabled = batchHeaders.length === 0;
}

function updateBatchUi() {
  const hasData = batchRows.length > 0 && batchHeaders.length > 0;
  batchControls.nameColumn.disabled = !hasData;
  batchControls.numberColumn.disabled = !hasData;
  batchControls.exportButton.disabled = !hasData || !templateReady;
  batchControls.summary.textContent = hasData
    ? t("batchReady").replace("{count}", batchRows.length)
    : t("batchEmpty");
}

function spreadsheetRowsToData(rows) {
  const firstNonEmpty = rows.findIndex((row) => row.some((cell) => String(cell).trim() !== ""));
  if (firstNonEmpty < 0) return { headers: [], data: [] };

  const sourceHeaders = rows[firstNonEmpty];
  const widestRow = Math.max(...rows.slice(firstNonEmpty).map((row) => row.length));
  const headers = Array.from({ length: widestRow }, (_, index) => {
    const value = String(sourceHeaders[index] ?? "").trim();
    return value || `Column ${index + 1}`;
  });
  const data = rows
    .slice(firstNonEmpty + 1)
    .map((row) => headers.map((_, index) => String(row[index] ?? "").trim()))
    .filter((row) => row.some(Boolean));
  return { headers, data };
}

async function parseBatchFile(file) {
  if (!file || !window.XLSX) return;
  try {
    const workbook = XLSX.read(await file.arrayBuffer(), { type: "array", cellText: true });
    const sheet = workbook.Sheets[workbook.SheetNames[0]];
    const rows = XLSX.utils.sheet_to_json(sheet, { header: 1, defval: "", raw: false });
    const parsed = spreadsheetRowsToData(rows);
    batchHeaders = parsed.headers;
    batchRows = parsed.data;
    fillColumnSelect(batchControls.nameColumn, findSuggestedColumn(/name|姓名|名字/i, 0));
    fillColumnSelect(batchControls.numberColumn, findSuggestedColumn(/number|no\.?|编号|号码|序号/i, 1));
    updateBatchUi();
  } catch (error) {
    console.error(error);
    batchHeaders = [];
    batchRows = [];
    updateBatchUi();
    setStatus("sheetError");
  }
}

function canvasToBlob(sourceCanvas) {
  return new Promise((resolve, reject) => {
    sourceCanvas.toBlob((blob) => (blob ? resolve(blob) : reject(new Error("PNG encoding failed"))), "image/png");
  });
}

function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.style.display = "none";
  // Some browsers ignore clicks on detached download links.
  document.body.append(link);
  link.click();
  window.setTimeout(() => {
    link.remove();
    URL.revokeObjectURL(url);
  }, 3000);
}

function getBatchRecords() {
  const nameIndex = Number(batchControls.nameColumn.value);
  const numberIndex = Number(batchControls.numberColumn.value);
  if (!Number.isInteger(nameIndex) || !Number.isInteger(numberIndex)) return [];
  return batchRows
    .map((row) => ({ name: row[nameIndex] ?? "", number: row[numberIndex] ?? "" }))
    .filter((record) => record.name || record.number);
}

async function downloadBatchZip() {
  if (isFilePage) {
    setStatus("localServerRequired");
    return;
  }
  if (!window.JSZip) {
    setStatus("sheetError");
    return;
  }
  const nameLayer = layers.find((layer) => layer.role === "name");
  const numberLayer = layers.find((layer) => layer.role === "number");
  if (!nameLayer || !numberLayer) {
    setStatus("batchMissingLayers");
    return;
  }

  const records = getBatchRecords();
  if (records.length === 0) {
    setStatus("batchMissingColumns");
    return;
  }

  const originalText = { name: nameLayer.text, number: numberLayer.text };
  const zip = new JSZip();
  batchControls.exportButton.disabled = true;
  batchControls.progress.hidden = false;
  batchControls.progress.max = records.length;
  batchControls.progress.value = 0;

  try {
    for (const [index, record] of records.entries()) {
      nameLayer.text = record.name;
      numberLayer.text = record.number;
      render();
      const blob = await canvasToBlob(canvas);
      const indexPart = String(index + 1).padStart(3, "0");
      const filename = `${indexPart}-${safeFilenamePart(record.name, "name")}-${safeFilenamePart(record.number, "number")}.png`;
      zip.file(filename, blob);
      batchControls.progress.value = index + 1;
      setStatus("batchProcessing", { current: index + 1, total: records.length });
      await new Promise((resolve) => window.requestAnimationFrame(resolve));
    }

    nameLayer.text = originalText.name;
    numberLayer.text = originalText.number;
    render();
    setStatus("batchZipping");
    const archive = await zip.generateAsync(
      { type: "blob", compression: "DEFLATE", compressionOptions: { level: 6 } },
      (metadata) => {
        batchControls.progress.max = 100;
        batchControls.progress.value = metadata.percent;
      },
    );
    downloadBlob(archive, `nameplates-${new Date().toISOString().slice(0, 10)}.zip`);
    setStatus("batchDone", { count: records.length });
  } catch (error) {
    console.error(error);
    nameLayer.text = originalText.name;
    numberLayer.text = originalText.number;
    render();
    setStatus("fileError");
  } finally {
    batchControls.progress.hidden = true;
    updateBatchUi();
  }
}

Object.values(controls).forEach((control) => {
  control.addEventListener("input", updateSelectedLayerFromInspector);
  control.addEventListener("change", updateSelectedLayerFromInspector);
});

document.querySelector("#addTextButton").addEventListener("click", addTextLayer);
document.querySelector("#addImageButton").addEventListener("click", () => document.querySelector("#imageUpload").click());
document.querySelector("#imageUpload").addEventListener("change", (event) => {
  addImageLayer(event.target.files?.[0]);
  event.target.value = "";
});
document.querySelector("#fontUpload").addEventListener("change", (event) => loadCustomFont(event.target.files?.[0]));
document.querySelector("#loadSystemFontsButton").addEventListener("click", loadSystemFonts);
document.querySelector("#resetButton").addEventListener("click", reset);
document.querySelector("#downloadButton").addEventListener("click", downloadPng);
batchControls.file.addEventListener("change", (event) => {
  parseBatchFile(event.target.files?.[0]);
  event.target.value = "";
});
batchControls.nameColumn.addEventListener("change", updateBatchUi);
batchControls.numberColumn.addEventListener("change", updateBatchUi);
batchControls.exportButton.addEventListener("click", downloadBatchZip);

document.querySelectorAll(".preview-tab").forEach((tab) => {
  tab.addEventListener("click", () => {
    document.querySelectorAll(".preview-tab").forEach((item) => item.classList.toggle("active", item === tab));
    document.querySelectorAll(".preview-view").forEach((view) => view.classList.remove("active"));
    document.querySelector(`#${tab.dataset.view}View`).classList.add("active");
  });
});

language.addEventListener("change", () => {
  applyTranslations();
  syncInspector();
  setStatus("ready");
});

template.addEventListener("load", async () => {
  try {
    await Promise.all([
      document.fonts.load('430px "ZCOOL KuaiLe"'),
      document.fonts.load('410px "Anton"'),
    ]);
    templateReady = true;
    reset();
    if (isFilePage) setStatus("localServerRequired");
  } catch (error) {
    console.error(error);
    setStatus("error");
  }
});

template.addEventListener("error", () => setStatus("error"));
applyTranslations();
updateFileModeNotice();
updateBatchUi();
setStatus("loading");
template.src = "assets/template-clean.png";
